#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Bob Dodd
# SPDX-License-Identifier: GPL-3.0-only

"""Split docs/AFDS-SPECIFICATION.md into the site's specification pages.

The specification is the single source of truth. This script re-presents
it; it never adds, removes, or rewords a normative sentence. It is run
from the accessible-by-design repository and writes into a checkout of
the a11ybob-website repository, whose generated files are committed
there so the site builds with no cross-repository dependency.

    python3 tools/site/build-spec-pages.py ../a11ybob-website

What it does, and why each transform is needed:

- Splits the document at its `##` boundaries into one page per Part,
  plus the status page and the annex. Clause numbers are global, so the
  split carries no meaning and no clause is renumbered.
- Turns every clause heading into an HTML heading with a stable numeric
  id, because the site has no rehype-slug and the specification promises
  a stable anchor derived from the clause number.
- Demotes heading levels by one, because the page supplies the h1.
- Rewrites markdown tables as the site's scroll-region table markup.
  The site does not load remark-gfm, so a markdown table would render as
  literal pipes.
- Wraps fenced code in a keyboard-reachable scroll region.
- Turns internal clause and part references into links to the page that
  now carries them.
- Emits contents.json, from which the landing page builds the table of
  contents and the navigation builds its list, so neither is retyped.
"""

import json
import os
import re
import sys

SRC = "docs/AFDS-SPECIFICATION.md"
BASE = "/adaptation/afds/specification"

# Page slug, the `##` heading it starts at, and the short label used in
# navigation. Order is the document's order.
PAGES = [
    ("status", "Status of this document", "Status"),
    ("part-1", "Part I. Purpose and model", "Part I"),
    ("part-2", "Part II. The component contract", "Part II"),
    ("part-3", "Part III. The method profiles", "Part III"),
    ("part-4", "Part IV. Serialisation", "Part IV"),
    ("annex-a", "Annex A (informative). Relationship to Open Packaging "
                "Conventions", "Annex A"),
]

BANNER = (
    "<!-- Generated from docs/AFDS-SPECIFICATION.md by\n"
    "     tools/site/build-spec-pages.py in bobdodd/accessible-by-design.\n"
    "     Do not edit this file. Edit the specification and run the\n"
    "     generator again. -->\n\n"
)

CLAUSE_HEADING = re.compile(r"^(#{3,5})\s+(\d+(?:\.\d+)*)(\.?)\s+(.*)$")
PLAIN_HEADING = re.compile(r"^(#{3,5})\s+(.*)$")


def anchor_for(number: str) -> str:
    """23 -> c23; 23.2 -> c23-2; 29.3.1 -> c29-3-1."""
    return "c" + number.replace(".", "-")


def slugify(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s or "section"


def escape(text: str) -> str:
    return (text.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;"))


def inline_to_html(text: str) -> str:
    """Convert the inline markdown used in this document to HTML.

    Needed only inside generated HTML blocks (table cells), because
    markdown inside a raw HTML block is not parsed as markdown.
    Code spans are protected first so their contents are never treated
    as emphasis or as a link.
    """
    spans: list[str] = []

    def stash(m: re.Match[str]) -> str:
        spans.append("<code>" + escape(m.group(1)) + "</code>")
        return f"\x00{len(spans) - 1}\x00"

    text = re.sub(r"`([^`]+)`", stash, text)
    text = escape(text)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\*([^*]+)\*", r"<em>\1</em>", text)
    return re.sub(r"\x00(\d+)\x00", lambda m: spans[int(m.group(1))], text)


# The longest link text the column will take without the nowrap rule on
# links pushing it past the measure. Beyond this the shortener falls
# back to a coarser form rather than breaking the text.
MAX_LINK_TEXT = 36


def shorten_autolinks(line: str) -> str:
    """Rewrite a bare `<https://...>` as a link with readable text.

    The document cites its sources as `Author, *Title*. <URL>`, which is
    right on the page and in the Word build but wrong on the web: links
    on this site do not wrap, so a bare URL of any length overflows the
    column and breaks reflow. The site's convention is to show the tail
    of the path instead and carry the full URL in the href, so that is
    what is generated here. No reference loses its address.
    """

    def rewrite(m: re.Match[str]) -> str:
        url = m.group(1)
        rest = re.sub(r"^https?://", "", url).rstrip("/")
        host, _, path = rest.partition("/")
        bare_host = re.sub(r"^www\.", "", host)
        if not path:
            text = bare_host
        else:
            segments = [s for s in path.split("/") if s]
            candidates = [
                "/".join(segments[-2:]),
                segments[-1],
                bare_host,
            ]
            text = next(
                (c for c in candidates if len(c) <= MAX_LINK_TEXT),
                bare_host,
            )
        return f"[{text}]({url})"

    return re.sub(r"<(https?://[^>\s]+)>", rewrite, line)


def split_row(line: str) -> list[str]:
    return [c.strip() for c in line.strip().strip("|").split("|")]


def render_table(rows: list[str], label: str) -> list[str]:
    header = split_row(rows[0])
    body = [split_row(r) for r in rows[2:]]
    out = [
        f'<div class="scroll-region" role="region" '
        f'aria-label="{escape(label)}" tabindex="0">',
        '<table class="comparison-table">',
        "<thead>",
        "<tr>",
    ]
    out += [f'<th scope="col">{inline_to_html(c)}</th>' for c in header]
    out += ["</tr>", "</thead>", "<tbody>"]
    for cells in body:
        out.append("<tr>")
        for i, cell in enumerate(cells):
            html = inline_to_html(cell)
            if i == 0 and len(header) > 1:
                out.append(f'<th scope="row">{html}</th>')
            else:
                out.append(f"<td>{html}</td>")
        out.append("</tr>")
    out += ["</tbody>", "</table>", "</div>", ""]
    return out


def main() -> int:
    if len(sys.argv) != 2:
        sys.stderr.write(f"usage: {sys.argv[0]} <path-to-site-checkout>\n")
        return 2
    site = sys.argv[1]
    out_dir = os.path.join(site, "content", "specification")
    if not os.path.isdir(os.path.join(site, "content")):
        sys.stderr.write(f"not a site checkout: {site}\n")
        return 2
    os.makedirs(out_dir, exist_ok=True)

    text = open(SRC, encoding="utf-8").read()
    text = re.sub(r"^<!--.*?-->\n+", "", text, flags=re.S)
    lines = text.split("\n")

    # ---- pass one: split into pages, and record where each clause lives
    starts: dict[str, int] = {}
    for i, line in enumerate(lines):
        if line.startswith("## "):
            for slug, heading, _ in PAGES:
                if line[3:].strip() == heading:
                    starts[slug] = i
    missing = [s for s, _, _ in PAGES if s not in starts]
    if missing:
        sys.stderr.write(f"headings not found for: {missing}\n")
        return 1

    order = sorted(starts.items(), key=lambda kv: kv[1])
    bounds: dict[str, tuple[int, int]] = {}
    for n, (slug, begin) in enumerate(order):
        end = order[n + 1][1] if n + 1 < len(order) else len(lines)
        bounds[slug] = (begin, end)

    home: dict[str, str] = {}          # clause number -> page slug
    titles: dict[str, str] = {}        # clause number -> title
    contents: list[dict[str, object]] = []
    for slug, heading, label in PAGES:
        begin, end = bounds[slug]
        clauses: list[dict[str, str]] = []
        for line in lines[begin:end]:
            m = CLAUSE_HEADING.match(line)
            if m and len(m.group(1)) == 3:
                number, title = m.group(2), m.group(4).strip()
                home[number] = slug
                titles[number] = title
                clauses.append({
                    "number": number,
                    "title": title,
                    "anchor": anchor_for(number),
                })
            elif m:
                home[m.group(2)] = slug
                titles[m.group(2)] = m.group(4).strip()
        contents.append({
            "slug": slug,
            "heading": heading,
            "label": label,
            "clauses": clauses,
        })

    part_home = {
        "I": "part-1", "II": "part-2", "III": "part-3", "IV": "part-4",
    }

    def link_references(line: str) -> str:
        """Point internal clause and part references at their page."""
        spans: list[str] = []

        def stash(m: re.Match[str]) -> str:
            spans.append(m.group(0))
            return f"\x00{len(spans) - 1}\x00"

        # Protect code spans, existing links, and HTML attributes.
        line = re.sub(r"`[^`]+`", stash, line)
        line = re.sub(r"\[[^\]]*\]\([^)]*\)", stash, line)
        line = re.sub(r'(?:href|id|aria-label)="[^"]*"', stash, line)

        def clause(m: re.Match[str]) -> str:
            word, number = m.group(1), m.group(2)
            root = number.split(".")[0]
            slug = home.get(number) or home.get(root)
            if not slug:
                return m.group(0)
            return f"[{word} {number}]({BASE}/{slug}#{anchor_for(number)})"

        line = re.sub(r"\b(clause|Clause)\s+(\d+(?:\.\d+)*)\b", clause, line)

        def part(m: re.Match[str]) -> str:
            slug = part_home[m.group(1)]
            return f"[Part {m.group(1)}]({BASE}/{slug})"

        line = re.sub(r"\bPart (I{1,3}V?|IV)\b(?!\.)", part, line)
        return re.sub(r"\x00(\d+)\x00", lambda m: spans[int(m.group(1))], line)

    # ---- pass two: render each page
    written = []
    for slug, heading, _ in PAGES:
        begin, end = bounds[slug]
        body = lines[begin + 1:end]
        out: list[str] = []
        i = 0
        current_label = heading
        seen_labels: dict[str, int] = {}
        while i < len(body):
            line = body[i]

            if line.startswith("```"):
                fence = [line]
                i += 1
                while i < len(body) and not body[i].startswith("```"):
                    fence.append(body[i])
                    i += 1
                if i < len(body):
                    fence.append(body[i])
                    i += 1
                out.append('<div class="scroll-region" tabindex="0">')
                out.append("<pre><code>")
                out.append("\n".join(escape(x) for x in fence[1:-1]))
                out.append("</code></pre>")
                out.append("</div>")
                out.append("")
                continue

            if line.startswith("|"):
                rows = []
                while i < len(body) and body[i].startswith("|"):
                    rows.append(body[i])
                    i += 1
                rows = [shorten_autolinks(r) for r in rows]
                if len(rows) >= 2:
                    n = seen_labels.get(current_label, 0) + 1
                    seen_labels[current_label] = n
                    label = current_label if n == 1 else \
                        f"{current_label}, table {n}"
                    out += render_table(rows, label)
                    continue
                out += rows
                continue

            m = CLAUSE_HEADING.match(line)
            if m:
                hashes, number = m.group(1), m.group(2)
                # The document writes a dot after a top-level clause
                # number and none after a subclause number. Preserve
                # whichever it used, so a heading on the page reads
                # exactly as it reads in the source.
                dot, title = m.group(3), m.group(4).strip()
                level = len(hashes) - 1        # page supplies the h1
                current_label = f"{number}{dot} {title}"
                out.append(
                    f'<h{level} id="{anchor_for(number)}">'
                    f"{number}{dot} {inline_to_html(title)}"
                    f"</h{level}>"
                )
                out.append("")
                i += 1
                continue

            m = PLAIN_HEADING.match(line)
            if m:
                hashes, title = m.group(1), m.group(2).strip()
                level = len(hashes) - 1
                current_label = title
                out.append(
                    f'<h{level} id="{slugify(title)}">'
                    f"{inline_to_html(title)}</h{level}>"
                )
                out.append("")
                i += 1
                continue

            out.append(link_references(shorten_autolinks(line)))
            i += 1

        page = "\n".join(out).strip() + "\n"
        page = re.sub(r"\n{3,}", "\n\n", page)
        page = BANNER + page
        path = os.path.join(out_dir, f"{slug}.md")
        open(path, "w", encoding="utf-8").write(page)
        written.append((slug, len(page.split("\n"))))

    index = {
        "version": "1.0.0",
        "source": SRC,
        "pages": contents,
    }
    with open(os.path.join(out_dir, "contents.json"), "w",
              encoding="utf-8") as f:
        json.dump(index, f, indent=2, ensure_ascii=False)
        f.write("\n")

    total = sum(len(p["clauses"]) for p in contents)  # type: ignore[arg-type]
    for slug, n in written:
        print(f"  {slug:8s} {n:5d} lines")
    print(f"contents.json: {total} clauses across {len(PAGES)} pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
