#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Bob Dodd
# SPDX-License-Identifier: GPL-3.0-only

"""Split docs/AFDS-USER-GUIDE.md into the site's user-guide pages.

The guide is the single source of truth for its own words. This
script re-presents it; it never adds, removes, or rewords a sentence.
It is run from the accessible-by-design repository and writes into a
checkout of the a11ybob-website repository, whose generated files are
committed there so the site builds with no cross-repository
dependency.

    python3 tools/site/build-guide-pages.py ../a11ybob-website

It is a sibling of build-spec-pages.py and deliberately a separate
script rather than a shared one, because the two documents are
structured differently: the specification is numbered and its anchors
come from clause numbers, while the guide is task-ordered and its
anchors come from section titles. The transforms they have in common
are small enough that sharing them would couple two generators whose
inputs may diverge.

What it does, and why each transform is needed:

- Splits the document at its `##` boundaries into one page per Part,
  plus the status page, the glossary appendix, and the references.
  The guide is not read in order, so the split follows its own Parts.
- Turns every section heading into an HTML heading with an id
  derived from its title, because the site has no rehype-slug and a
  section needs a stable anchor to be citable.
- Demotes heading levels by one, because the page supplies the h1.
- Rewrites markdown tables as the site's scroll-region table markup.
  The site does not load remark-gfm, so a markdown table would render
  as literal pipes.
- Wraps fenced code in a keyboard-reachable scroll region.
- Turns the guide's inline clause citations into links into the
  published specification, resolved from the specification's own
  generated contents.json, so a reader can get from an instruction to
  the normative text behind it. A citation whose clause cannot be
  resolved is left as written rather than guessed at.
- Turns references to the specification's Parts into links to the
  page that carries them.
- Emits contents.json, from which the landing page builds the table
  of contents and the navigation builds its list, so neither is
  retyped.
"""

import json
import os
import re
import sys

SRC = "docs/AFDS-USER-GUIDE.md"
BASE = "/adaptation/afds/user-guide"
SPEC_BASE = "/adaptation/afds/specification"

# Page slug and the `##` heading it starts at. Order is the document's
# order. There is no separate short label: the guide is not read in
# order, so a reader choosing a part from the navigation is choosing by
# subject, and "Part 5" alone does not say what the part is about. The
# navigation therefore carries the heading itself.
PAGES = [
    ("status", "Status of this guide"),
    ("part-1", "Part 1. Before you start"),
    ("part-2", "Part 2. What a design system is, and why accessibility "
               "drives this one"),
    ("part-3", "Part 3. Conformance, claims, and the three axes"),
    ("part-4", "Part 4. The component contract"),
    ("part-5", "Part 5. The method profiles"),
    ("part-6", "Part 6. The package"),
    ("part-7", "Part 7. Reading paths, mistakes, and what is open"),
    ("appendix-a", "Appendix A. Glossary"),
    ("references", "References"),
]

BANNER = (
    "<!-- Generated from docs/AFDS-USER-GUIDE.md by\n"
    "     tools/site/build-guide-pages.py in bobdodd/accessible-by-design.\n"
    "     Do not edit this file. Edit the guide and run the\n"
    "     generator again. -->\n\n"
)

HEADING = re.compile(r"^(#{3,5})\s+(.*)$")


def slugify(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s or "section"


def escape(text: str) -> str:
    return (text.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;"))


def inline_to_html(text: str) -> str:
    """Convert the inline markdown used in this document to HTML.

    Needed only inside generated HTML blocks (table cells and
    headings), because markdown inside a raw HTML block is not parsed
    as markdown. Code spans are protected first so their contents are
    never treated as emphasis or as a link.
    """
    spans: list[str] = []

    def stash(m: re.Match[str]) -> str:
        spans.append("<code>" + escape(m.group(1)) + "</code>")
        return f"\x00{len(spans) - 1}\x00"

    text = re.sub(r"`([^`]+)`", stash, text)
    text = escape(text)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\*([^*]+)\*", r"<em>\1</em>", text)
    return re.sub(r"\x00(\d+)\x00", lambda m: spans[int(m.group(1))], text)


def plain(text: str) -> str:
    """The heading text with its markdown markers removed.

    Used for contents.json and for a table's accessible name, where
    markup would be noise rather than meaning.
    """
    text = re.sub(r"`([^`]+)`", r"\1", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    return re.sub(r"\*([^*]+)\*", r"\1", text)


# The longest link text the column will take without the nowrap rule
# on links pushing it past the measure.
MAX_LINK_TEXT = 36


def shorten_autolinks(line: str) -> str:
    """Rewrite a bare `<https://...>` as a link with readable text.

    The document cites its sources as `Author, *Title*. <URL>`, which
    is right on the page and in the Word build but wrong on the web:
    links on this site do not wrap, so a bare URL of any length
    overflows the column and breaks reflow. The site's convention is
    to show the tail of the path instead and carry the full URL in the
    href. No reference loses its address.
    """

    def rewrite(m: re.Match[str]) -> str:
        url = m.group(1)
        rest = re.sub(r"^https?://", "", url).rstrip("/")
        host, _, path = rest.partition("/")
        bare_host = re.sub(r"^www\.", "", host)
        if not path:
            text = bare_host
        else:
            segments = [s for s in path.split("/") if s]
            candidates = [
                "/".join(segments[-2:]),
                segments[-1],
                bare_host,
            ]
            text = next(
                (c for c in candidates if len(c) <= MAX_LINK_TEXT),
                bare_host,
            )
        return f"[{text}]({url})"

    return re.sub(r"<(https?://[^>\s]+)>", rewrite, line)


def split_row(line: str) -> list[str]:
    return [c.strip() for c in line.strip().strip("|").split("|")]


def render_table(rows: list[str], label: str, link) -> list[str]:
    """Render a markdown table as the site's scroll-region table.

    Cells are passed through the citation linker before conversion,
    because a clause cited in a table is as much a citation as one
    cited in a sentence, and a reader should not have to leave the
    table to reach the clause.
    """
    header = split_row(rows[0])
    body = [split_row(r) for r in rows[2:]]
    out = [
        f'<div class="scroll-region" role="region" '
        f'aria-label="{escape(label)}" tabindex="0">',
        '<table class="comparison-table">',
        "<thead>",
        "<tr>",
    ]
    out += [f'<th scope="col">{inline_to_html(link(c))}</th>' for c in header]
    out += ["</tr>", "</thead>", "<tbody>"]
    for cells in body:
        out.append("<tr>")
        for i, cell in enumerate(cells):
            html = inline_to_html(link(cell))
            if i == 0 and len(header) > 1:
                out.append(f'<th scope="row">{html}</th>')
            else:
                out.append(f"<td>{html}</td>")
        out.append("</tr>")
    out += ["</tbody>", "</table>", "</div>", ""]
    return out


def clause_anchor(number: str) -> str:
    """23 -> c23; 23.2 -> c23-2; 29.3.1 -> c29-3-1."""
    return "c" + number.replace(".", "-")


def load_spec_home(site: str) -> dict[str, str]:
    """Clause number -> the specification page that carries it.

    Read from the specification's own generated index, so the guide's
    citations cannot point at a page split the specification no longer
    uses. Only top-level clause numbers are indexed there; a subclause
    resolves through its root, which is enough because a subclause is
    always on the page its clause is on.
    """
    path = os.path.join(site, "content", "specification", "contents.json")
    with open(path, encoding="utf-8") as f:
        contents = json.load(f)
    home: dict[str, str] = {}
    for page in contents["pages"]:
        for clause in page["clauses"]:
            home[clause["number"]] = page["slug"]
    return home


def main() -> int:
    if len(sys.argv) != 2:
        sys.stderr.write(f"usage: {sys.argv[0]} <path-to-site-checkout>\n")
        return 2
    site = sys.argv[1]
    out_dir = os.path.join(site, "content", "user-guide")
    if not os.path.isdir(os.path.join(site, "content")):
        sys.stderr.write(f"not a site checkout: {site}\n")
        return 2
    try:
        spec_home = load_spec_home(site)
    except FileNotFoundError:
        sys.stderr.write(
            "the specification pages have not been generated in that "
            "checkout; run build-spec-pages.py first\n")
        return 1
    os.makedirs(out_dir, exist_ok=True)

    text = open(SRC, encoding="utf-8").read()
    text = re.sub(r"^<!--.*?-->\n+", "", text, flags=re.S)
    lines = text.split("\n")

    # ---- pass one: split into pages, and record each page's sections
    starts: dict[str, int] = {}
    for i, line in enumerate(lines):
        if line.startswith("## "):
            for slug, heading in PAGES:
                if line[3:].strip() == heading:
                    starts[slug] = i
    missing = [s for s, _ in PAGES if s not in starts]
    if missing:
        sys.stderr.write(f"headings not found for: {missing}\n")
        return 1

    order = sorted(starts.items(), key=lambda kv: kv[1])
    bounds: dict[str, tuple[int, int]] = {}
    for n, (slug, begin) in enumerate(order):
        end = order[n + 1][1] if n + 1 < len(order) else len(lines)
        bounds[slug] = (begin, end)

    # Section anchors are derived from titles, so a page that repeats a
    # title has to disambiguate. The suffix is assigned in document
    # order and is therefore stable for as long as the order is.
    anchors: dict[tuple[str, int], str] = {}   # (slug, line) -> anchor
    contents: list[dict[str, object]] = []
    for slug, heading in PAGES:
        begin, end = bounds[slug]
        used: dict[str, int] = {}
        sections: list[dict[str, str]] = []
        for n in range(begin, end):
            m = HEADING.match(lines[n])
            if not m:
                continue
            title = plain(m.group(2).strip())
            base = slugify(title)
            seen = used.get(base, 0) + 1
            used[base] = seen
            anchor = base if seen == 1 else f"{base}-{seen}"
            anchors[(slug, n)] = anchor
            if len(m.group(1)) == 3:
                sections.append({"title": title, "anchor": anchor})
        contents.append({
            "slug": slug,
            "heading": heading,
            "sections": sections,
        })

    def link_references(line: str) -> str:
        """Link clause citations, and the guide's own Part references."""
        spans: list[str] = []

        def stash(m: re.Match[str]) -> str:
            spans.append(m.group(0))
            return f"\x00{len(spans) - 1}\x00"

        # Protect code spans, existing links, and HTML attributes.
        line = re.sub(r"`[^`]+`", stash, line)
        line = re.sub(r"\[[^\]]*\]\([^)]*\)", stash, line)
        line = re.sub(r'(?:href|id|aria-label)="[^"]*"', stash, line)

        def spec_link(number: str) -> str | None:
            slug = spec_home.get(number) or spec_home.get(number.split(".")[0])
            if not slug:
                return None
            return f"{SPEC_BASE}/{slug}#{clause_anchor(number)}"

        def clause(m: re.Match[str]) -> str:
            word, number = m.group(1), m.group(2)
            href = spec_link(number)
            if not href:
                return m.group(0)
            return f"[{word} {number}]({href})"

        def clauses(m: re.Match[str]) -> str:
            word, first, rest = m.group(1), m.group(2), m.group(3)

            def one(mm: re.Match[str]) -> str:
                href = spec_link(mm.group(0))
                return f"[{mm.group(0)}]({href})" if href else mm.group(0)

            head = one(re.match(r"\d+(?:\.\d+)*", first))  # type: ignore[arg-type]
            tail = re.sub(r"\d+(?:\.\d+)*", one, rest)
            return f"{word} {head}{tail}"

        # A list of clause numbers first, so its members are linked
        # individually rather than only the first of them.
        line = re.sub(
            r"\b(clauses|Clauses)\s+(\d+(?:\.\d+)*)"
            r"((?:(?:,|,? and)\s+\d+(?:\.\d+)*)+)",
            clauses, line)
        line = re.sub(r"\b(clause|Clause)\s+(\d+(?:\.\d+)*)\b", clause, line)

        def spec_part(m: re.Match[str]) -> str:
            roman = m.group(1)
            slug = {"I": "part-1", "II": "part-2",
                    "III": "part-3", "IV": "part-4"}[roman]
            return f"[Part {roman}]({SPEC_BASE}/{slug})"

        # Roman numerals are always the specification's Parts, so they
        # can be linked without ambiguity. The guide's own Parts are
        # Arabic, and those are deliberately left alone: the guide
        # refers to itself that way only once, while ECMA-376 Part 2
        # and ISO/IEC 29500 Part 2 are cited three times, and a link
        # that sent a reader from an external standard's part to a page
        # of this guide would be wrong.
        line = re.sub(r"\bPart (IV|III|II|I)\b(?!\.)", spec_part, line)
        return re.sub(r"\x00(\d+)\x00", lambda m: spans[int(m.group(1))], line)

    # ---- pass two: render each page
    written = []
    for slug, heading in PAGES:
        begin, end = bounds[slug]
        out: list[str] = []
        i = begin + 1
        current_label = heading
        seen_labels: dict[str, int] = {}
        while i < end:
            line = lines[i]

            if line.startswith("```"):
                fence = [line]
                i += 1
                while i < end and not lines[i].startswith("```"):
                    fence.append(lines[i])
                    i += 1
                if i < end:
                    fence.append(lines[i])
                    i += 1
                out.append('<div class="scroll-region" tabindex="0">')
                out.append("<pre><code>")
                out.append("\n".join(escape(x) for x in fence[1:]
                                     if not x.startswith("```")))
                out.append("</code></pre>")
                out.append("</div>")
                out.append("")
                continue

            if line.startswith("|"):
                rows = []
                while i < end and lines[i].startswith("|"):
                    rows.append(lines[i])
                    i += 1
                rows = [shorten_autolinks(r) for r in rows]
                if len(rows) >= 2:
                    n = seen_labels.get(current_label, 0) + 1
                    seen_labels[current_label] = n
                    label = current_label if n == 1 else \
                        f"{current_label}, table {n}"
                    out += render_table(rows, label, link_references)
                    continue
                out += rows
                continue

            m = HEADING.match(line)
            if m:
                hashes, title = m.group(1), m.group(2).strip()
                level = len(hashes) - 1        # page supplies the h1
                current_label = plain(title)
                out.append(
                    f'<h{level} id="{anchors[(slug, i)]}">'
                    f"{inline_to_html(title)}</h{level}>"
                )
                out.append("")
                i += 1
                continue

            out.append(link_references(shorten_autolinks(line)))
            i += 1

        page = "\n".join(out).strip() + "\n"
        page = re.sub(r"\n{3,}", "\n\n", page)
        page = BANNER + page
        path = os.path.join(out_dir, f"{slug}.md")
        open(path, "w", encoding="utf-8").write(page)
        written.append((slug, len(page.split("\n"))))

    index = {
        "version": "1.0.0",
        "source": SRC,
        "pages": contents,
    }
    with open(os.path.join(out_dir, "contents.json"), "w",
              encoding="utf-8") as f:
        json.dump(index, f, indent=2, ensure_ascii=False)
        f.write("\n")

    total = sum(len(p["sections"]) for p in contents)  # type: ignore[arg-type]
    for slug, n in written:
        print(f"  {slug:11s} {n:5d} lines")
    print(f"contents.json: {total} sections across {len(PAGES)} pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
